name: commit-build-test

on: [push]

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  test-without-integration:
    runs-on: ubuntu-latest
    container: quarkchaindocker/pyquarkchain:mainnet1.1.1

    steps:
    - uses: actions/checkout@v4
    - name: Install Project Dependencies
      run: PYTHONPATH=/code/pyquarkchain pip3 install -e .

    - name: Run py.test tests excluding integration test
      run: |
        cd qkchash && make clean && make && cd -
        python3 -m pytest --ignore quarkchain/cluster/tests/test_cluster.py

  evm-tests-runner-1:
    runs-on: ubuntu-latest
    container: quarkchaindocker/pyquarkchain:mainnet1.1.1

    steps:
    - uses: actions/checkout@v4
    - name: Install Project Dependencies
      run: PYTHONPATH=/code/pyquarkchain pip3 install -e .

    - name: Run EVM tests - runner 1
      run: |
        find fixtures/GeneralStateTests -name "*.json" | sort | sed -n 'n;p' | xargs cp --parents -t /tmp/ && python3 quarkchain/evm/tests/test_state.py /tmp/fixtures/GeneralStateTests > /dev/null;

  evm-tests-runner-2:
    runs-on: ubuntu-latest
    container: quarkchaindocker/pyquarkchain:mainnet1.1.1

    steps:
    - uses: actions/checkout@v4
    - name: Install Project Dependencies
      run: PYTHONPATH=/code/pyquarkchain pip3 install -e .

    - name: Run EVM tests - runner 2
      run: |
        find fixtures/GeneralStateTests -name "*.json" | sort | sed -n 'p;n' | xargs cp --parents -t /tmp/ && python3 quarkchain/evm/tests/test_state.py /tmp/fixtures/GeneralStateTests > /dev/null;

  test-integration-and-qkc-specific-state:
    runs-on: ubuntu-latest
    container: quarkchaindocker/pyquarkchain:mainnet1.1.1

    steps:
    - uses: actions/checkout@v4
    - name: Install Project Dependencies
      run: PYTHONPATH=/code/pyquarkchain pip3 install -e .

    - name: Run py.test tests only on integration test
      run: |
        cd qkchash && make clean && make && cd -
        python3 -m pytest quarkchain/cluster/tests/test_cluster.py

    - name: Run QuarkChain-specific EVM tests
      run: |
        python3 quarkchain/evm/tests/test_state.py fixtures/QuarkChainStateTests/
