name: qkcli-integration-test

on:
  push:
    branches:
      - master

jobs:
  mnt-test-using-qkcli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # In the future, add it as a submodule
          repository: QuarkChain/qkcli
          ref: master
          token: ${{ secrets.GH_TOKEN }}
          path: qkcli
      - uses: actions/setup-go@v5
        with:
          go-version: "~1.14.4"
      - run: go version
      - run: cd qkcli && go build && go install && cd tester && bash parallel_executor.sh
