name: qkcli-integration-test

on: [push]
# on:
  # push:
    # branches:
      # - master

jobs:
  mnt-test-using-qkcli:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # In the future, add it as a submodule
          repository: QuarkChain/qkcli
          ref: master
          token: ${{ secrets.QKCLI_PAT }}
          path: qkcli
      - uses: actions/setup-go@v2
        with:
          go-version: "~1.14.4"
      - run: go version
      - run: cd qkcli && go build
      - run: cd qkcli && go install
      - run: cd qkcli/tester && bash parallel_executor.sh
